### ISSUE TITLE
I am trying to apply to spring5 legacy

### ISSUE THREAD

**Issue by callor** [mbosecke/pebble-example-spring#2]
I am trying to apply to spring5 legacy

but
com.mitchellbosecke.pebble.PebbleEngine
com.mitchellbosecke.pebble.spring.servlet.PebbleViewResolver

It is set to bean, but an error occurs in the class setting below.
Please help me

**Comment by ebussieres** [comment]
@callor 

Sorry, I really don't understand what is your problem with the information that you provided. Did you check the documentation ? Do you use spring-boot ? Can you provide some code snippet or better your application that is not working ?

Documentation for spring-boot is here : https://pebbletemplates.io/wiki/guide/spring-boot-integration/

There's also some examples 
- https://github.com/PebbleTemplates/spring-petclinic

**Comment by callor** [comment]
Thank you

I Want Spring Legacy Project Not work boot

The code I made

pom.xml

	<properties>
		<java-version>1.8</java-version>
		<org.springframework-version>5.2.5.RELEASE</org.springframework-version>

		<org.spring-security-version>5.2.3.RELEASE</org.spring-security-version>
		<io.pebble.version>3.1.4</io.pebble.version>

		<org.jasypt-version>1.9.3</org.jasypt-version>
		<org.slf4j-version>1.7.30</org.slf4j-version>

		<org.aspectj-version>1.6.10</org.aspectj-version>
	</properties>

	
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>${org.springframework-version}</version>
			<exclusions>
				
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<version>${org.springframework-version}</version>
		</dependency>
		
		<dependency>
			<groupId>io.pebbletemplates</groupId>
			<artifactId>pebble-spring5</artifactId>
			<version>${io.pebble.version}</version>
		</dependency>

		
		<dependency>
			<groupId>io.pebbletemplates</groupId>
			<artifactId>pebble-spring</artifactId>
			<version>${io.pebble.version}</version>
			<type>pom</type>
		</dependency>

servlet-context.xml

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

	<bean id="messageSource"
		class="org.springframework.context.support.ReloadableResourceBundleMessageSource">
		<property name="defaultEncoding" value="UTF-8" />
		<property name="basenames">
			<list>
				<value>classpath:/egovframework/message/message</value>
			</list>
		</property>
	</bean>
	<bean id="localeResolver"
		class="org.springframework.web.servlet.i18n.SessionLocaleResolver">
		<property name="defaultLocale" value="ko">
		</property>
	</bean>

	<bean id="springExtension"
		class="com.mitchellbosecke.pebble.spring.extension.SpringExtension">
		<constructor-arg ref="messageSource" />
	</bean>

	<bean id="classLoader" class="java.lang.ClassLoader">
	</bean>

	<bean id="pabbleEngine" class="com.mitchellbosecke.pebble.PebbleEngine">
		<property name="extension" ref="springExtension"/>
		<property name="loader" ref="classLoader"/>
	</bean>

	<bean id="viewResolver"
		class="com.mitchellbosecke.pebble.spring.servlet.PebbleViewResolver">
		<property name="prefix" value="/WEB-INF/templates/"/>
		<property name="suffix" value=".html"/>
		<property name="pebbleEngine" ref="pebbleEngine" />
	</bean>

servlet-context.xml 
I'm still having problems

**Comment by ebussieres** [comment]
Can you provide a stacktrace ??? Or better, a link to your repository

**Comment by callor** [comment]
Thank you

my repository

https://github.com/callor/Spring_Pebble.git

**Comment by callor** [comment]
> Can you provide a stacktrace ??? Or better, a link to your repository

please Help me
